CREATE TABLE [dbo].[UserGroups]
(
	[Id] INT CONSTRAINT PK_UserGroups_Id PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[IsDeleted] BIT NOT NULL CONSTRAINT DF_UserGroups_IsDeleted DEFAULT 0,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL CONSTRAINT DF_UserGroups_CreatedOn DEFAULT GETUTCDATE(),
    [UpdatedBy] UNIQUEIDENTIFIER NULL,
    [UpdatedOn] DATETIME2 NULL
)
