// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CottonPrompt.Infrastructure.Entities;

public partial class Order
{
    public int Id { get; set; }

    public string OrderNumber { get; set; }

    public bool Priority { get; set; }

    public string Concept { get; set; }

    public int PrintColorId { get; set; }

    public int DesignBracketId { get; set; }

    public int OutputSizeId { get; set; }

    public int UserGroupId { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerStatus { get; set; }

    public Guid? ArtistId { get; set; }

    public string ArtistStatus { get; set; }

    public Guid? CheckerId { get; set; }

    public string CheckerStatus { get; set; }

    public int? OriginalOrderId { get; set; }

    public int? ChangeRequestOrderId { get; set; }

    public bool IsCoolDown { get; set; }

    public DateTime? CompletedOn { get; set; }

    public DateTime? AcceptedOn { get; set; }

    public DateTime? ChangeRequestedOn { get; set; }

    public DateTime? SentForPrintingOn { get; set; }

    public DateTime? ReportedOn { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual User Artist { get; set; }

    public virtual Order ChangeRequestOrder { get; set; }

    public virtual User Checker { get; set; }

    public virtual OrderDesignBracket DesignBracket { get; set; }

    public virtual ICollection<Order> InverseChangeRequestOrder { get; set; } = new List<Order>();

    public virtual ICollection<Order> InverseOriginalOrder { get; set; } = new List<Order>();

    public virtual ICollection<InvoiceSectionOrder> InvoiceSectionOrders { get; set; } = new List<InvoiceSectionOrder>();

    public virtual ICollection<OrderDesign> OrderDesigns { get; set; } = new List<OrderDesign>();

    public virtual ICollection<OrderImageReference> OrderImageReferences { get; set; } = new List<OrderImageReference>();

    public virtual ICollection<OrderReport> OrderReports { get; set; } = new List<OrderReport>();

    public virtual ICollection<OrderStatusHistory> OrderStatusHistories { get; set; } = new List<OrderStatusHistory>();

    public virtual Order OriginalOrder { get; set; }

    public virtual OrderOutputSize OutputSize { get; set; }

    public virtual OrderPrintColor PrintColor { get; set; }

    public virtual UserGroup UserGroup { get; set; }
}