// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CottonPrompt.Infrastructure.Entities;

public partial class User
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public DateTime LastLoggedOn { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Order> OrderArtists { get; set; } = new List<Order>();

    public virtual ICollection<Order> OrderCheckers { get; set; } = new List<Order>();

    public virtual ICollection<OrderReport> OrderReportCheckers { get; set; } = new List<OrderReport>();

    public virtual ICollection<OrderReport> OrderReportReportedByNavigations { get; set; } = new List<OrderReport>();

    public virtual ICollection<OrderReport> OrderReportResolvedByNavigations { get; set; } = new List<OrderReport>();

    public virtual ICollection<UserGroupUser> UserGroupUsers { get; set; } = new List<UserGroupUser>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}